name:                aws-v4sign-hs
version:             0.1.0.0
github:              "githubuser/aws-v4sign-hs"
license:             BSD3
author:              "Yuan Wang"
maintainer:          "yuan.wang@workiva.com"
copyright:           "2018 Yuan Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aws-v4sign-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aws-v4sign-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-v4sign-hs

tests:
  aws-v4sign-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-v4sign-hs
